server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mcay51/ecommerce-config
          default-label: main
          search-paths: 
            - '*service'

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/ 